version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
#    ports:
#      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --log-level info
        --reload
        --timeout 120
        "labs_web.runserver:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    depends_on:
      - redis
      - postgres
      - mongodb
    volumes:
      - '/home/$USER/website_vol:/storage'
      - '.:/labs_web'
    ports:
      - '8000:8000'

  celery:
    image: 'labs_web_website:latest'
    depends_on:
      - redis
      - postgres
      - mongodb
    command: celery worker -l info -A labs_web.celery
    volumes:
      - '/home/$USER/website_vol:/storage'

  data:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: alex
      POSTGRES_USER: alex
      POSTGRES_DB: labs_by_web_db

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /home/$USER/mongo_docker/data/db:/data/db
#      ports:
#          - 27017:27017
    command: mongod # --quiet

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - celery
      - website
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  redis:
  postgres:

