version: '3.3'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - "./.volumes/redis/:/data/"
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --log-level info
        --reload
        --timeout 120
        "labs_web.runserver:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    depends_on:
      - redis
      - postgres
      - mongodb
    volumes:
      - './.volumes/site:/storage'
      - '.:/labs_web'
    ports:
      - '8000:8000'

  celery:
    image: 'labs_web_website:latest'
    depends_on:
      - redis
      - postgres
      - mongodb
    command: celery worker -l info -A labs_web.celery
    volumes:
      - './.volumes/site:/storage'

  postgres:
    image: postgres:latest
    volumes:
      - "./.volumes/pg/:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: alex
      POSTGRES_USER: alex
      POSTGRES_DB: labs_by_web_db

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "./.volumes/mongo/data/db:/data/db"
    ports:
      - 27017:27017
    command: mongod # --quiet

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - celery
      - website
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  alembic:
    image: 'labs_web_website:latest'
    volumes:
    - ".:/labs_web"
    entrypoint: alembic -n alembic:docker

  minio1:
    image: minio/minio:RELEASE.2020-06-12T00-06-19Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2020-06-12T00-06-19Z
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2020-06-12T00-06-19Z
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2020-06-12T00-06-19Z
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2: